### ISSUE TITLE
Allow the option to change the focus target when the dropdown menu opens.

### ISSUE THREAD

**Issue by LuisAverhoff** [kaliber5/ember-bootstrap#1028]
My use case is that I have a custom dropdown that I've built using the dropdown component that `ember-bootstrap` provides. This custom dropdown has a searchbox input similar to the one `bootstrap-select` gives you. When the dropdown opens, I want it to focus on the searchbox instead of the top level container. This is impossible at the moment because of this particular function in the `DropdownMenu` component.

```
@action
  setFocus() {
    let menuElement = document.getElementById(`${this.get('dropdownElementId')}__menu`);
   // unless I override the id of the top level container to something else that doesn't end with menu
  // it will always autofocus. If override the id, it breaks functionality.
    if (menuElement) {
      menuElement.focus();
    }
  }
```

This default makes sense for users who just want to use the dropdown as is but maybe you can include an `autofocus` property to allow consumers the option to disable this and have them decide what to focus when the dropdown opens. Of course the default value of this property would default to true so that regular users dont have to worry about setting this property.

```
@action
  setFocus() {
    let menuElement = document.getElementById(`${this.get('dropdownElementId')}__menu`);
    if (menuElement && this.autofocus) {
      menuElement.focus();
    }
  }
```

Another option is to have a  public property for querying the element that the user wants to focus.

```
@action
  setFocus() {
    const dropdownElementToFocus = this.dropdownElementSelector ? this.document.getElementById(this.dropdownElementSelector ) : this.document.getElementById(`${this.get('dropdownElementId')}__menu`);

    if (dropdownElementToFocus) {
      dropdownElementToFocus.focus();
    }
  }
```

**Comment by simonihmig** [comment]
That seems like a reasonable request, thanks for opening this! I'll look into this, maybe as part of fixing #972.

**Comment by simonihmig** [comment]
The change in #1029 (which fixes the mentioned different issue) should at least *partially* solve your problem, as focus will not be changed anymore when the dropdown is rendered "in place" (the default). Only when `renderInPlace` is set to false, this issue would pop again. But I would prefer to tackle this later when v4 is out, if needed, rather than adding new APIs now. 

@LuisAverhoff can you see if this change would solve your problem?

**Comment by jelhan** [comment]
Wondering if a `autofocusTargetSelector` would be a more powerful. It could still disable autofocus if `null` but would additionally allow to change the autofocus target - e.g. to an input element inside the dropdown.

**Comment by simonihmig** [comment]
> Wondering if a autofocusTargetSelector would be a more powerful.

Yes, I considered this as well. But thought that using a modifier (there is [https://github.com/qonto/ember-autofocus-modifier](ember-autofocus-modifier)) instead of having to add classes/data attributes and assembling CSS selectors is the more appropriate way in "the new world". So the dropdown component would just have to "get out of the way".

**Comment by LuisAverhoff** [comment]
@simonihmig Just updated and now I'm able to use the autofocus modifier to target any element in the dropdown that I want to focus on. Thanks for the quick fix. I'll close this issue.
