### ISSUE TITLE
`<Carousel>` component is missing in API docs

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#1301]
The `<Carousel>` component is missing in latest API docs. Not exactly sure since when.

**Comment by bvedad** [comment]
It was working on `version v4.0.0-rc.2`  with `"ember-cli-yuidoc": "^0.8.8"` but it has been broken in `v4.0.0-rc.3` after upgrading `"ember-cli-yuidoc": "^0.9.1"`. After more investigation, I have found that the issue is starting to occur on `0.9.0` due to the following changes https://github.com/cibernox/ember-cli-yuidoc/compare/v0.8.8...v0.9.0
I had a look at comments on the `bs-carousel.hbs` file and I have found that we have unnecessary ``` characters which are causing issues. I am creating MR to resolve it.
