### ISSUE TITLE
`BsModalComponent` renders footer as a `form` tag

### ISSUE THREAD

**Issue by kboucher** [kaliber5/ember-bootstrap#1427]
`BsModalComponent` renders footer as a `form` tag. This can be observed even in the simple modal demo here: https://www.ember-bootstrap.com/components/modal

1. Click Open Modal
1. Observe `<form class="modal-footer">` in the rendered markup

**Comment by jelhan** [comment]
It is like this since years. It was added by commit c1ef184a5fdf7f57fe96721fee08e43c70909fa9 in 2015. It seems as if it was added to support using a `<form>` within the modal. But it is a bug for sure as it does not match Bootstrap markup.

Not sure if we should consider changing it to `<div>` a breaking change. It may break CSS selectors relying on `.modal-footer` being a `<form>` and not a `<div>`.
