### ISSUE TITLE
cannot change build targets

### ISSUE THREAD

**Issue by thibaut-code** [kaliber5/ember-bootstrap#1437]
if you change the build targets as described in https://cli.emberjs.com/release/advanced-use/build-targets/
the production build will fail

**Comment by simonihmig** [comment]
Could you please add more details here:
* what are you changing your targets to?
* how is it failing the build (error message + stack trace)

**Comment by thibaut-code** [comment]
change your targets to 

```
 module.exports = {
  browsers: [
    'last 1 edge versions',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};

```
do  `ember build --environment=production`

you get a the following error:

```
Build Error (UglifyWriter)

Unexpected token: punc (.)
```

**Comment by simonihmig** [comment]
It seems uglifyJs is choking on the use of optional chaining (`foo?.bar`), which commonly happens when it is *not* transpiled away by babel (because you removed IE11) support. UglifyJs is not maintained anymore AFAIK. Seems you haven't updated your app's dependencies according to the latest Ember blueprints. So either run `ember-cli-update`, or just replace `ember-cli-uglify` with `ember-cli-terser` (terser is the maintained replacement for uglify, which is able to parse all ES-latest features), that should fix it!
