### ISSUE TITLE
Road to 5.0

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1592]
- [x] drop BS3 support
- [x] drop IE11 support #1596 
- [x] BS5 support #1494 
- [x] make BS5 the default
- [x] drop node 10 #1595 
- [x] other breaking changes: https://github.com/kaliber5/ember-bootstrap/issues?q=is%3Aissue+is%3Aopen+label%3Abreaking

**Comment by simonihmig** [comment]
@jelhan everything checked off! 👆 🚀

**Comment by jelhan** [comment]
I'm only wondering if we should consider #1438 as a breaking change and fix as part of v5.

**Comment by vst** [comment]
We have been refactoring our (largish, >50Kloc) codebase. We took advantage of this to test the application with ember-bootstrap v5.x since its first alpha release in early August.

I am not suggesting that our experience is a reliable source for drawing conclusions, but just as a *quick feedback*: We have not seen any regressions or bad surprises since the first beta is launched.

**Comment by Polve** [comment]
Will v5 be compatible with ember4?

**Comment by jelhan** [comment]
> Will v5 be compatible with ember4?

It is. Tests are passing for Ember v4 using latest release candidate.
