### ISSUE TITLE
Expected output of the first tab example

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#174]
```
{{#bs-tab type=type.id}}
  {{#bs-tab-pane title="Tab 1"}}
    <p>Tab 1 Content</p>
  {{/bs-tab-pane}}
  {{#bs-tab-pane title="Tab 2"}}
    <p>...</p>
  {{/bs-tab-pane}}
{{/bs-tab}}
```

If I simply drop this into a component, I don't get "tabs".. I get a ul/li structure that is something like:
```
  Tab 1

  Tab 2

Tab 1 Content
```

But if I implement the custom tabs 'variety' I definitely get tabs as I expect from bootstrap etc.

is this expected behavior?

(this is on pre-1.0)

**Comment by simonihmig** [comment]
It think this is due to a bad example in the docs. Will have to fix this!

The `type` property of `bs-tab` should be either "tabs" or "pills", defaulting to "tabs". The `type=type.id` part come from a tab example in the addons dummy app, where you could switch the tab style based on an array of tab styles. As I said I'll have to fix this example.

It should be fine as soon as you remove this `type=type.id` part!

**Comment by rstudner** [comment]
Wow! Light Speed - thanks @simonihmig
