### ISSUE TITLE
Upgrading to 1.0.0-alpha3 and bootstrap

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#218]
I'm using ember-cli-bootstrap-sassy so that I can have a variables.scss file and fully configure my bootstrap theme (in project).

When I install 1.0.0-alpha3, and include the ember-bootstrap/bootstrap sass file... *all* of the styles in my app get greatly changed.

I saw when installing it, it installed bootstrap-sass.

Just sort of curious if you have any thought as to what might be going on :)?  

(the rest of the upgrade/contextual syntax etc, went great)

**Comment by simonihmig** [comment]
Hm, not sure. Have you removed ember-cli-bootstrap-sassy from package.json and its `@import "bootstrap";` from app.scss? Your variable.scss gets imported before ember-bootstrap/bootstrap?

**Comment by rstudner** [comment]
I hadn't removed anything, but the ember-bootstrap/bootstrap I had being imported *first* (our of all the files).  I'll go try to move that around etc.  Thanks for the response

(btw, I realize this isn't a "ember-bootstrap" bug per se, just trying to get ahead of any upgrade/integration issues others may run into as well heh).

**Comment by srvance** [comment]
@rstudner Early feedback is greatly appreciated. Thank you for the effort.

**Comment by rstudner** [comment]
Alrighty, I can close this one out / sorry for the delay.

Basically, the workaround here is: "delete bootstrap-sassy and just use ember-bootstrap".  Which, in hindsight, is dead obvious.

Deleted bootstrap-sassy, put my variables file directly before @import "ember-bootstrap/bootstrap" and everything works.

I'm on alpha4 and so far haven't found any bugs that are negatively affecting me.

How "production ready" do you guys consider this thing (I realize the question i'm asking, given that this is an alpha.. was mostly looking for a level of confidence not a guarentee hah)

**Comment by simonihmig** [comment]
Good to hear. 

Regarding stability we have several apps in production, some even with the older 0.x series. So should be no problem. If you have not done so, I would strongly suggest to use yarn and its `yarn.lock` file (not just because of ember-bootstrap, I think it's always  useful). This way you do not get unexpected updates in your dependencies, so they are only updated when you are actively doing so and push a new commit. 

So we reserve the right to introduce some breaking changes while still in alpha, but I actually don't expect that to happen...
