### ISSUE TITLE
How to use theme with ember-bootstrap

### ISSUE THREAD

**Issue by Caltor** [kaliber5/ember-bootstrap#237]
I'm using ember-bootstrap add-on which is working fine but I would like to use the Cerulean theme from https://bootswatch.com/cerulean/. If I just overwrite the .CSS files in bower_components/bootstrap/dist/css then I expect they will be overwritten the next time I do a `bower install` or upgrade ember. How do I get around that please?

**Comment by srvance** [comment]
If you're not using LESS or SASS, you may want to consider it for a cleaner solution. Then you could just import the theme variable files in your `app.{less,scss}`.

There are bower packages for it, so you could consider installing it that way instead of `bootstrap`; you would just need to change the path references.

Alternatively, put it in your `/public` directory, your choice, but perhaps `/public/styles`, and `@import` it in your `app.css`.

**Comment by Caltor** [comment]
I'm not currently using LESS or SASS but I will look into it.

How will Ember or the browser know to use the styles from the custom CSS file though rather than the ones from inside bootstrap-ember?

I see from http://stackoverflow.com/q/10036977/470014 that @Import is slower than <link> in index.html as the CSS files can't be loaded in parallel.

**Comment by srvance** [comment]
`ember-bootstrap` doesn't care where the styles come from. We just apply the correct classes to the right components. That will change a little bit once the Bootstrap 4 support is merged, but you could use Bower package aliasing to get around that using something like `bower install bootstrap=bootswatch --save`.

**Comment by simonihmig** [comment]
@Caltor If that theme is available as a bower package, you can install it alongside bootstrap, and import it in your `ember-cli-build.js`. See https://ember-cli.com/user-guide/#stylesheets

If this already contains all the necessary Bootstrap CSS, you can opt out of including the default Bootstrap CSS by setting `importBootstrapCSS` to false, see http://www.ember-bootstrap.com/#/getting-started
