### ISSUE TITLE
Enable validations only when validation addon is installed

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#240]
Currently `hasValidator` is true when having `ember-cp-validations` installed, but `ember-bootstrap-cp-validations` is missing. Maybe `hasValidator` has just to be defined false in `ember-bootstrap` and overriden in the validation addons (`ember-bootstrap-cp-validations` is already doing that, `ember-bootstrap-changeset-validations` and `ember-bootstrap-validations`need to be updated though)

**Comment by shuriu** [comment]
I think this is actually a bug, not an enhancement.

I read the docs and saw the bit about installing `ember-bootstrap-cp-validations`, but figured that because the addon is alpha and everything is still in flux, and that the fields validate, but incorrectly, I surely must be missing something and that validations are in fact inside THIS addon.
