### ISSUE TITLE
RFE: Auto collapse Navbar during navigation

### ISSUE THREAD

**Issue by wireframe** [kaliber5/ember-bootstrap#317]
Recollapsing the nav-bar when a user clicks on a link would be a great feature enhancement.  Hooking into the ember router `didTransition` event should be possible to accomplish this.

**Comment by simonihmig** [comment]
Makes sense! 

Will have to figure out how the API should look like. Not sure if making this depend on the router is the best way. What if a link just triggers an action without a route change? Might be better to trigger this on any click on a `nav.item`?

**Comment by Techn1x** [comment]
I found that using didTransition() caused stutters in the collapse animation when I clicked on a slower loading page (specifically, with a map view)

Instead, I used willTransition() and the collapse animation is much smoother (because it is triggered before loading the slow page)

I agree that it would be better if it wasn't dependent on the router in the first place, but here is my basic implementation that seems to work well for me;

template
```
{{#bs-navbar collapsed=collapseValue as |navbar|}}
    ....
{{/bs-navbar}}
```

controller
`collapseValue: true, // Start navbar as collapsed`

route
```
actions: {
    willTransition() {
        // Collapse navbar on every transition
        this.controllerFor('application').set('collapseValue', true);
        return true; // Bubble
    }
}
```

**Comment by Techn1x** [comment]
Would something like this be possible? (perhaps there might be nav items that you don't want to collapse the navbar on..)
{{nav.item collapseNavbar=true}}

**Comment by danidr** [comment]
I have proposed an interface in the referenced issue above, #321, where the collapseNavbar property @Techn1x mentioned is handled in the `{{nav.link-to}}` instead.
Also, the workaround above is fine when using the navbar directly in a "standard" template (not a component), but when putting it inside a component, that would need a lot of variables passing around. Yep, I do believe this would be a very nice enhancement 😊

**Comment by wireframe** [comment]
@Techn1x and @danidr I *really* like the proposal to have the setting on the link vs a global mixin!
