### ISSUE TITLE
Better document that bootstrap.js is not used

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#330]
See https://github.com/kaliber5/ember-bootstrap/issues/125#issuecomment-304004660

**Comment by michelboaventura** [comment]
I've spent an afternoon on this issue, trying to figure out why my drop-down wasn't working before realizing this addon doesn't include ``bootstrap.js``. It would be great to have this as a warning on the docs :+1:

**Comment by Caltor** [comment]
@michelboaventura Ditto!

**Comment by srvance** [comment]
@Caltor, @michelboaventura: I have submitted a PR for some doc enhancements. I can't add you as reviewers, but I would appreciate any feedback you would like to give.

@simonihmig Can we allow them to review this?

**Comment by simonihmig** [comment]
> Can we allow them to review this?

According to [this](https://help.github.com/articles/requesting-a-pull-request-review/) Github page, everybody with read access should be allowed as reviewers. Maybe just the autocomplete is only picking existing contributors?

So anyway, feel free to review/comment in any feasible way! ;)

**Comment by michelboaventura** [comment]
I've reviewed the text, thanks!

Importing bootstrap.js is harder than it should, because ember is moving away from bower and adopting yarn, but it doesn't allow us to import any file from within node_modules, and if we use browserify we need to use something like ``import bootstrap from 'npm:bootstrap``, which triggers a warning on eslint, since ``bootstrap`` is never used. So the only way I could resolve this was putting bootstrap.js inside vendor's folder and importing it from there.

Since I'm quite new to ember, do you have a better way of doing this?

Thanks

**Comment by Caltor** [comment]
@michelboaventura Agreed. I opted to import from bower in the end and revisit it when import from node_modules becomes possible in the future. I did toy with putting it in the vendor folder myself but I figured at least using bower would make updates easier / less manual (not that it's big deal).

**Comment by Caltor** [comment]
@srvance @simonihmig I've reviewed the changes and posted my comments. I've never done this before so I hope I've done it right!
