### ISSUE TITLE
Navbar collapsed property binding

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#372]
A very minor issue, but I noticed when updating my webapp to the 1.0.0-beta.2, that the upgrade actually broke my (very simple) manual approach to navbar collapse (likely due to the now built in method).

For example, this code works in beta.1 to collapse the navbar, but does not work in beta.2 (it seems the navbar's `collapsed` property isn't listening to changes or something?)
template
```handlebars
{{#bs-navbar collapsed=collapseValue as |navbar|}}
    {{#navbar.content}}
        {{#navbar.nav as |nav|}}
            {{#nav.item}}{{#nav.link-to "dashboard" collapseNavbar=false}}Dashboard{{/nav.link-to}}{{/nav.item}}
        {{/navbar.nav}}
    {{/navbar.content}}
{{/bs-navbar}}
```

controller
`collapseValue: true, // Start navbar as collapsed`

route
```
actions: {
    willTransition() {
        // Collapse navbar on every transition
        this.controllerFor('application').set('collapseValue', true);
        return true; // Bubble
    }
}
```

While I don't need to bind the `collapsed` property of the navbar anymore, I do believe it's broken, and someone else out there might need it to work

**Comment by simonihmig** [comment]
I updated the navbar example with a check box controlling the collapsed state: http://www.ember-bootstrap.com/#/components/navbars

The `collapsed` property was private before, and there was not care taken to make it one-way only. Now it is, so when the navbar is expanding, you will not see this in your `collapseValue`, unless you listen for the `onCollapse(d)` / `onExpand(ed)` actions, where you can update that value. So when you are setting `collapseValue` to true, but it was still true (because not being updated), it might not trigger the collapsing.

I am closing this, as as I said the `collapsed` property is only public as of beta.2, and using its current API things should work as in the example...

**Comment by Techn1x** [comment]
Oops, didn't realise it was private before! My bad, thanks for clearing that up.
