### ISSUE TITLE
Dropdowns do not work

### ISSUE THREAD

**Issue by bailey86** [kaliber5/ember-bootstrap#40]
It looks to me like the dropdown menus do not work.

Have I missed something or is this an issue?

**Comment by ruzrig** [comment]
The {{bs-select}} doesn't also work for me. 
Using this code,


                {{bs-select 
                  content=listPayment
                  optionValuePath="content.paymentTermId"
                  optionLabelPath="content.description"
                }}

**Comment by simonihmig** [comment]
There are no issues that I know of. If used like described in the [API Docs](http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Dropdown.html) or in the addon's [dummy app](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/dummy/app/templates/dropdown.hbs), it should work. Otherwise please provide the relevant code sample.

**Comment by simonihmig** [comment]
@ruzrig Please don't mix issues here. File a seperate one if needed!
Try this:

```hbs
{{bs-select 
  content=listPayment
  optionValuePath="paymentTermId"
  optionLabelPath="description"
}}
```
