### ISSUE TITLE
Support BS4-beta.3

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#518]
Tracking issue for https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.3:

- [x] Update `devDependency` and default blueprint for new version
- [x] dropLeft/dropRight #517 
- [x] `.modal-dialog-centered`
- [x] fix tooltip/popover arrow positioning tests

**Comment by omairvaiyani** [comment]
@simonihmig Would you recommend switching to BS4 with ember-bootstrap on a production app? Are there any areas you need help implementing?

**Comment by srvance** [comment]
@omairvaiyani It's still considered experimental at least until Boostrap 4 is stable. Even in the beta series of BS4 releases, we've had things break. If you're pinning versions and comfortable with the possibility of bugs and breakage, we'd love to get the usage and feedback, but there's a risk that you need to be willing to accept.

**Comment by omairvaiyani** [comment]
That's understandable - I've usually worked around bugs even in BS3 versions, so I'll give this a shot and report back. One of my aims was to reduce reliance on jQuery so that we can integrate fastboot in the near future to our platform - are you convinced that a stripped down version of BS4 without jQuery would be useable and productive?

**Comment by srvance** [comment]
That all depends on what components you need. Ember-bootstrap is pretty complete. Work on carousel is in PR right now. I haven’t done a complete inventory recently, but ember-bootstrap has near-complete coverage of bootstrap.js. The only difference in coverage between its BS3 and BS4 support would be due to differences between BS3 and BS4 that have not been addressed. It also depends on what else you use jQuery for.

**Comment by simonihmig** [comment]
As @srvance said we don't consider it really stable, but mainly because Bootstrap 4 itself is not stable yet. This very issue here exists because some things changed (or rather have been added) between Bootstrap 4 beta.3 and beta.3, not because ember-bootstrap's support is unreliable in any way. And we have one app in production using Bootstrap 4 beta, so I would say yes, you can use it. But be prepared to have to fix things when upgrading Bootstrap itself! (e.g. they might change the name of some Sass variables, so that would be totally unrelated to ember-bootstrap, but still require some fixing if you used it)

FWIW, the Bootstrap 4 dependency ember-bootstrap adds to your `package.json` is pinned at a specific version for these reasons, so you wouldn't get any "accidental" updates, even when not using a lock file.

> One of my aims was to reduce reliance on jQuery so that we can integrate fastboot in the near future to our platform

A bit off topic, but a) you can use FastBoot with a jQuery bundled app though, and b) ember-bootstrap does not use *any* jQuery. Just in case this was not clear...
