### ISSUE TITLE
Add 'closeButton' option to bs-modal

### ISSUE THREAD

**Issue by grizzyzz** [kaliber5/ember-bootstrap#573]
Hi!  The bs-modal components work very well.  However, the big -1 in my opinion is that currently you are unable to remove the top right 'x' close button in bs-modal (it is an option for the simple modal); As far as i can tell..

Fortunately very easy fix.

---
Output from `components/base/bs-modal-simple.js` [#L94](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-modal-simple.js#L94)
Should be copied into `components/base/bs-modal.js`
```
/**
   * Display a close button (x icon) in the corner of the modal header.
   *
   * @property closeButton
   * @type boolean
   * @default true
   * @public
   */
  closeButton: true,
```

--- 
Output from `templates/components/common/bs-modal.hbs` [#L19](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/common/bs-modal.hbs#L19)
Should be changed too
```
header=(component "bs-modal/header" title=title closeButton=closeButton onClose=(action "close"))
```

**Comment by simonihmig** [comment]
@grizzyzz this is not needed. `bs-modal-simple` is supposed to be used without any contextual components, that's why some common options are available on this component itself.

But for `bs-modal` this is different, because it yields the contextual components (header, body, footer), and you can set *every* supported (public) property directly (see API) on these components. Like this:

```hbs
{{#bs-modal as |modal|}}
  {{#modal.header closeButton=false}}
    <h4 class="modal-title">Title</h4>
  {{/modal.header}}
...
{{/bs-modal}}
```

Hope that works for you! Closing this for now...

**Comment by grizzyzz** [comment]
Oh hey!  I am smacking my head against the wall this morning for not even thinking about passing it directly into the header context... 

Cheers!

**Comment by simonihmig** [comment]
No problem! I know that feeling too well! ;)
