### ISSUE TITLE
Support for Ember-Data errors

### ISSUE THREAD

**Issue by oswaldoacauan** [kaliber5/ember-bootstrap#64]
http://emberjs.com/api/data/classes/DS.Errors.html

**Comment by offirgolan** [comment]
Since all validations have been moved to 3rd party addons, this issue should be closed. If you are using ember-cp-validations, it already has DS.Errors integration, otherwise this issue should be opened with ember-validations since the scope of this addon only handles displaying errors that are in the `errors` array.

**Comment by simonihmig** [comment]
@oswaldoacauan Is there really a need for supporting only ember-data errors without any client side validation? Otherwise I think @offirgolan's suggestion makes sense: use ember-cp-validations (see https://github.com/offirgolan/ember-bootstrap-cp-validations) for client side validation + DS.Errors support!

**Comment by oswaldoacauan** [comment]
I fixed that overwriting the errors template. But thanks for the suggestions.
