### ISSUE TITLE
loop inside bs-dropdown-menu dont work

### ISSUE THREAD

**Issue by viniciuscb** [kaliber5/ember-bootstrap#73]
Hi, I've tried to make a dynamic menu , however with no success. In the code below, the each-in inside the bs-dropdown-menu does not change when I change the variable. 

```
        {{#each-in filters as |dimension keywords|}}
          {{#bs-dropdown tagName="li"}}
          {{#bs-dropdown-toggle}}{{dimension}} <span class="caret"></span>{{/bs-dropdown-toggle}}
          {{#bs-dropdown-menu}}
          {{#each-in keywords as |keyword val|}}
            <li><a href="#">{{keyword}}</a></li>
          {{/each-in}}
          {{/bs-dropdown-menu}}
          {{/bs-dropdown}}
        {{/each-in}}
```

The variable is:

```
  filters: {
    contaNivel2: { 'MANUTENCAO': true , "ONE MORE FILTER": true}
    contaNivel1: {"OTHER FILTER": true}
  },
```

**Comment by simonihmig** [comment]
I guess it is because you are using a POJO (plain old javascript object) instead of a real `Ember.Object` that supports bindings and observers, so Ember does not know about changes in the deeper levels of your object, especially if you directly change the object instead of using Ember's `set()` method on a real `Ember.Object` (just speculating as I cannot see how the object changes are done). 

However I am pretty sure it is not related to ember-bootstrap, replace the dropdown with some basic nested `<ul>` structure and it will probably behave just the same!

Please reopen if I should be really wrong on this!
