### ISSUE TITLE
Improve the semantics of form's onInvalid action

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#731]
Picking up what was discussed [here](https://github.com/kaliber5/ember-bootstrap/pull/730#discussion_r243525543):
* validations should be shown after an eventually returned Promise from `onInvalid` has settled
* provide some means to skip showing the validations based on the action's return value

*Potentially a breaking change!*

**Comment by simonihmig** [comment]
@jelhan would you be interested in working on this, as this was based on your suggestion?

**Comment by jelhan** [comment]
@simonihmig, thanks a lot for picking this one up. I'm sorry for not replying earlier. Haven't had much time the last weeks.

> provide some means to skip showing the validations based on the action's return value

I think this needs some more thoughts. E.g. it's not clear yet, when the validations should be shown again. Also we haven't seen an actual use case yet. If an application is able to resolve the validation errors automatically, it should also update the validation state. In that case there isn't any need to hide the validations. If the validation shouldn't be shown before a transaction caused by an invalid form submission, a long-pending promise could be returned. The same applies if some user interaction should be done on an invalid submission (e.g. showing a modal). Last but not least applications should be able to implement this on their own without overriding internal APIs as soon as we provide a way to control the visibility of validations in general (#364). So we should focus on that one first in my opinion.

**Comment by simonihmig** [comment]
I agree, see also my comment here https://github.com/kaliber5/ember-bootstrap/pull/820#issue-283854425.

I will add a note to #364 and keep that issue to track controlling the visibility of validations.

**Comment by simonihmig** [comment]
> validations should be shown after an eventually returned Promise from onInvalid has settled

Implemented by #820, closing this.
