### ISSUE TITLE
Test selector support is broken for BsModal in v3.0.0-rc.0

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#846]
Test selectors can't be used anymore on `BsModal` and `BsModalSimple` if invoked using classic syntax.

```hbs
{{#bs-modal data-test-foo="bar"}}...{{/bs-modal}}
```

throws 

> Assertion Failed: ember-test-selectors could not bind data-test-* properties on <twiddle@component:bs-modal-simple::ember145> automatically because tagName is empty. If you did this intentionally, see https://github.com/simplabs/ember-test-selectors#usage-in-computed-properties for instructions on how to disable this assertion.

I guess it's the same issue as discussed here: https://github.com/kaliber5/ember-bootstrap/pull/845

**Comment by simonihmig** [comment]
Yes, the modal has been made tagless to support splattributes, without applying them twice. You actually catched that :) https://github.com/kaliber5/ember-bootstrap/pull/795#discussion_r275112797

> I guess it's the same issue as discussed here: #845

Yeah, it seems we cannot support properly applying splattributes *and* test selectors w/ curly invocation at the same time.

As we do not explicitly support `ember-test-selectors`, at least as far as our "SemVer contract" is concerned, and properly supporting angle brackets is basically "non-negotiable", we do have to introduce these "breaking" changes nevertheless I think. But at least we should mention these explicitly in the Changelog, and suggest refactoring to angle brackets to "fix" this.

Do you agree?

Btw, unless having `renderInPlace=true` that test-selector would not make much sense, as that would be applied to an empty `div` (prior to 3.0.0-rc.0), while the actual modal is wormholed, so not "affected" by that test selector. Or do I miss something?

**Comment by jelhan** [comment]
> As we do not explicitly support `ember-test-selectors`, at least as far as our "SemVer contract" is concerned, and properly supporting angle brackets is basically "non-negotiable", we do have to introduce these "breaking" changes nevertheless I think. But at least we should mention these explicitly in the Changelog, and suggest refactoring to angle brackets to "fix" this.
> 
> Do you agree?

This would mean that an application using test selectors must be upgraded to angle bracket component invocation syntax for Ember Bootstrap components on the same time as upgrading Ember Bootstrap. That's far from being optimal. Allowing incremental adoption of new patterns is a major arguments for Ember's stability without stagnation approach.

If we don't have any other option that introducing that breaking change, we should do it for all components at once. Everything else would be a very bad developer experience in my opinion.

But I can't believe that there isn't any work-a-round. Isn't there an API to get the element which the attributes are applied to in Ember or Glimmer component? At least the Glimmer VM must have that information. If it's available through some (private?) API, the issue could be fixed upstream at Ember Test Selectors. I will try to find some time the next days to investigate that one or at least open an issue at Ember Test Selectors repository.

> Btw, unless having `renderInPlace=true` that test-selector would not make much sense, as that would be applied to an empty `div` (prior to 3.0.0-rc.0), while the actual modal is wormholed, so not "affected" by that test selector. Or do I miss something?

Good question. Not worked on that code recently. Just updated that application to see if `3.0.0-rc.0` breaks something and noticed the failing tests due to that assertion. `grep "renderInPlace" app/ config/ tests/` returned nothing, so I think some more magic might be included. Will have a look at it as soon as possible.

**Comment by simonihmig** [comment]
> This would mean that an application using test selectors must be upgraded to angle bracket component invocation syntax for Ember Bootstrap components on the same time as upgrading Ember Bootstrap. 

Well, no. This is only the case where we changed a component to be tagless (to be able to use `...attributes` without applying them twice). If the component still has a root element, ember-test-selectors will continue to work fine. And if it was tagless before, then there is no change.

Looking at the [changes from 2.8.0 to 3.0.0-rc.0](https://github.com/kaliber5/ember-bootstrap/compare/v2.8.0...master) I can see only `bs-modal` that was changed from having a `div` root element to being tagless. And as said before, that empty `<div></div>` was useless, and applying test selector to it as well, *AFAICT*

So for `bs-modal` the changes here actually make using test-selectors properly (on the wormholed real modal element) possible (when using angle brackets), which wasn't the case before.

I tested the latest release with a few of our apps, and the only issue I encountered was that other form issue.

So I don't see a big problem here!?

> Isn't there an API to get the element which the attributes are applied to in Ember or Glimmer component?

Sorry, not following you here. To do what?

**Comment by jelhan** [comment]
> Looking at the changes from 2.8.0 to 3.0.0-rc.0 I can see only bs-modal that was changed from having a div root element to being tagless. And as said before, that empty <div></div> was useless, and applying test selector to it as well, AFAICT

Test selectors are working fine with `{{bs-modal}}` in `v2.8.0` without any hacks. Did not investigated how it's working but this CodeSandbox demonstrates that it does: https://codesandbox.io/s/my-app-xeysi?fontsize=14&initialpath=%2Ftests&module=%2Ftests%2Fintegration%2Fcomponents%2Fmy-component-test.js

> > Isn't there an API to get the element which the attributes are applied to in Ember or Glimmer component?
> 
> Sorry, not following you here. To do what?

Opened an issue at Ember Test Selectors repo with more details about that one: https://github.com/simplabs/ember-test-selectors/issues/383

**Comment by simonihmig** [comment]
> Test selectors are working fine with {{bs-modal}} in v2.8.0 without any hacks. Did not investigated how it's working but this CodeSandbox demonstrates that it does

Your test is working because there is no `div#ember-bootstrap-wormhole` that the model can render into, so it falls back effectively to `renderInPlace=true`: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-modal.js#L264. For integration tests we have to put that wormhole into DOM explicitly: https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-modal-simple-test.js#L421

In that mode the (not removed) div is indeed wrapping the actual modal. But in wormholed mode - which should be how a modal works in reality - that is not the case, so the test selector does not make sense there.

**Comment by jelhan** [comment]
> Your test is working because there is no `div#ember-bootstrap-wormhole` that the model can render into, so it falls back effectively to `renderInPlace=true`: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-modal.js#L264. For integration tests we have to put that wormhole into DOM explicitly: https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-modal-simple-test.js#L421

I'm not sure if I miss something obvious, but it's also working for acceptance tests out of the box: https://codesandbox.io/s/using-test-selectors-with-bs-modal-simple-xeysi?fontsize=14&initialpath=%2Ftests&module=%2Ftests%2Facceptance%2Fapplication-test.js

**Comment by simonihmig** [comment]
>  but it's also working for acceptance tests out of the box

You are right. I had to dig into it a bit to recall what's going on...
* the wormhole destination is *not* created in test mode explicitly: https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L259
* some context why that is: https://github.com/kaliber5/ember-bootstrap/pull/647#issue-209974760
* So in test mode, all modals/popovers/tooltips/dropdown don't render in a wormhole *by default*. Which by itself is not so nice actually, given that you are not testing the "real thing". 
* that's why the test selectors applied to the former wrapping div work in tests, kind of *accidentally*

Given we have the opportunity now to introduce breaking changes, we maybe should rethink this!?

Fortunately we have @cibernox to the rescue, who probably had to face similar issues with `ember-basic-dropdown`, and his approach looks like this:
* also omit the default wormhole div in test mode: https://github.com/cibernox/ember-basic-dropdown/blob/4264bbbb1943b5e4ae4d535e183771005d28b907/index.js#L27
* instead to effectively falling back to `renderInPlace=true` in tests, the wormhole container is set to the test container's root element: https://github.com/cibernox/ember-basic-dropdown/blob/4264bbbb1943b5e4ae4d535e183771005d28b907/addon/components/basic-dropdown.js#L228-L248
* so while they are wormholed to some other place than in the real app, they *are*  wormholed in tests, and the user/test should not make assumptions about the wormhole destination anyway, IMHO

We might follow the same idea, what do you think?

This *might* introduce some more breaking changes, in case where users had (accidentally) baked some assumptions about the DOM location of their modals in their tests. But it will still affect only tests, not the real app, and the default test behavior seems more sane than before.

**Comment by jelhan** [comment]
> Given we have the opportunity now to introduce breaking changes, we maybe should rethink this!?

:100: I didn't had time to go into the details you described about how `ember-basic-dropdown` fixes that issue but it sounds like a good approach. Having test selectors working out of the box in `3.0.0` with angle bracket component invocation syntax while increasing the test coverage is actually quite nice.

If there is the ability to add an easy to toggle fallback to omit the wormhole location (and implicitly falling back to `renderInPlace`) we should do that and document it in changelog. That would be an awesome possibility to allow incremental adoption. But if it's to hard, it would be fine for me to tell everybody that they must refactor to angle bracket component invocation syntax if using test selectors.

**Comment by simonihmig** [comment]
Here is an implementation of the "new" behavior in tests: #851
